### ISSUE TITLE
Support for `eslint-define-config`

### ISSUE THREAD

**Issue by Shinigami92** [un-ts/eslint-plugin-import-x#23]
Right now, `eslint-plugin-i` does not support `eslint-define-config` or `typescript types` at all.  
Does `eslint-plugin-i` want to support it natively? (This would require shipping `.d.ts` files), or should I add https://github.com/eslint-types/define-config-plugin-types/tree/main/types/i (alongside https://github.com/eslint-types/define-config-plugin-types/tree/main/types/import)?

_Coming from https://github.com/vitejs/vite/pull/15569_

**Comment by JounQin** [comment]
Thanks @Shinigami92! :heart:

I'd love to definitely.

But I also have some questions

1. <del>Do you mean to re-export `@eslint-types/import` as typings at this repository?</del> It seems we can't, the plugin name is hard coded.
2. If not, should we mark `@eslint-types/import` as dependency for reusing some types? Or we just write ourselves?
3. Do you want to maintain it here? It would be great if you can join the org or project.

**Comment by Shinigami92** [comment]
@JounQin could you make a review of https://github.com/eslint-types/define-config-plugin-types/pull/42
I just mostly copied over the files from `<root>/types/import` and replaced `import/` with `i/` as well as the github links in the settings type.
Then I ran `pnpm run preflight` to generate the rest via script.

Can you especially check the settings? Also why do the rules (`<root>/types/i/types.d.ts`) contain links to https://github.com/import-js/eslint-plugin-import instead of https://github.com/un-es/eslint-plugin-i?

**Comment by JounQin** [comment]
I didn't view all through but it should just be fine, because the most functionalities are all the same, ecpect modern deps.

> Also why do the rules (<root>/types/i/types.d.ts) contain links to https://github.com/import-js/eslint-plugin-import instead of https://github.com/un-es/eslint-plugin-i?

Because this fork aims to be an alias actually. Imagine a user have a legacy ESLint config using `eslint-plugin-import` inside, and in project root level it's using `eslint-plugin-i`, there will be duplicate deps: `import` + `i`, this is what I don't want.

The recommended usage is always:

```sh
npm install -D eslint-plugin-import@npm:eslint-plugin-i@latest
```

See also https://github.com/import-js/eslint-import-resolver-typescript/pull/248

---

Besides, I remembered that, the setting prefix is still `import` due to strategy as above. Please check https://github.com/un-es/eslint-plugin-i/issues/17.

**Comment by Shinigami92** [comment]
This MR can be closed. I'm thinking of deprecating `eslint-define-config` in favor of `tseslint.config` (https://typescript-eslint.io/getting-started/#step-2-configuration)
